import { z } from "zod";

/** Single registry shared by the DF06 readiness contract and DF-P1 telemetry. */
export const DETERMINISTIC_READINESS_REASON_CODES_V1 = [
  "BUYING_INTENT_MISSING",
  "BUYING_INTENT_SCOPE_MISMATCH",
  "PRODUCT_UNRESOLVED",
  "PRODUCT_AMBIGUOUS",
  "PRODUCT_SCOPE_INVALID",
  "CART_CAPACITY_EXCEEDED",
  "CLAIM_MISSING",
  "CLAIM_STALE",
  "CLAIM_SCOPE_MISMATCH",
  "CLAIM_CONFLICT",
  "STATE_REVISION_MISMATCH",
  "CART_REQUIRED",
  "CART_STATE_BINDING_MISSING",
  "CART_VERSION_MISMATCH",
  "ORDER_PREVIEW_REQUIRED",
  "ORDER_PREVIEW_MISMATCH",
  "EFFECT_NOT_SUPPORTED",
  "DETERMINISTIC_EVIDENCE_MISSING",
] as const;

export const DeterministicReadinessReasonCodeV1Schema = z.enum(
  DETERMINISTIC_READINESS_REASON_CODES_V1,
);

