import { z } from "zod";
import { DecisionObservabilityV1Schema } from "./decision-observability.js";

export const RealtimeDecisionEventTypeSchema = z.enum([
  "PRODUCT_RESOLVED",
  "PRODUCT_MATCHED",
  "PRICE_CARD_SENT",
  "SIZE_CONSULT_STARTED",
  "BUYING_SIGNAL_DETECTED",
  "BUYING_SIGNAL_COMMITTED",
  "BUYING_SIGNAL_RETRACTED",
  "READY_TO_BUY",
  "ORDER_INFO_REQUESTED",
  "CHECKOUT_DETAILS_MISSING",
  "CLARIFICATION_REQUESTED",
  "CHECKOUT_COMPLETED",
  "ORDER_PREVIEW_CREATED",
  "PURCHASE_CONFIRMATION_DETECTED",
  "PURCHASE_CONFIRMATION_REJECTED",
  "PURCHASE_CONFIRMED",
  "ORDER_INTENT_CREATED",
  "HANDOFF",
  "HANDOFF_REQUESTED",
  "GUARD_BLOCKED",
  "NO_REPLY",
  "NO_REPLY_SELECTED",
  "WAVE2_STRATEGY_SELECTED",
  "WAVE2_BARRIER_DETECTED",
]);

const BuyingSignalReasonSchema = z.enum([
  "DIRECT_PURCHASE_VERB",
  "CONFIRMED_SIZE",
  "CONFIRMED_COLOR",
  "SHIP_REQUEST",
  "COMPONENT_SELECTION",
]);

export const RealtimeDecisionEventV1Schema = z.object({
  schemaVersion: z.literal(1),
  eventId: z.string().uuid(),
  conversationHash: z.string().min(16).max(128),
  eventKeyHash: z.string().regex(/^[a-f0-9]{64}$/u),
  eventType: RealtimeDecisionEventTypeSchema,
  origin: z.string().max(64).nullable(),
  reasonCodes: z.array(z.string().min(1).max(128)).max(20),
  releaseId: z.string().min(1).max(128),
  promptVersion: z.string().min(1).max(128),
  modelVersion: z.string().max(128).nullable(),
  policyVersion: z.string().max(256).nullable(),
  catalogVersion: z.string().max(128).nullable(),
  mode: z.enum(["DRY_RUN", "LIVE"]),
  productId: z.string().max(128).nullable(),
  intent: z.string().max(64).nullable(),
  stage: z.string().max(64).nullable(),
  action: z.string().max(64).nullable(),
  occurredAt: z.string().datetime(),
  details: z.object({
    productResolutionOrigin: z.string().max(64).nullable(),
    buyingSignalReasons: z.array(BuyingSignalReasonSchema).max(5),
    guardReasonCodes: z.array(z.string().min(1).max(128)).max(20),
    factsStatus: z.enum(["OK", "STALE", "AMBIGUOUS", "NOT_FOUND", "ERROR"]).nullable(),
    factsReasonCode: z.string().max(128).nullable(),
    salesCycleStageBefore: z.string().max(64).nullable(),
    salesCycleStageAfter: z.string().max(64).nullable(),
    outboundMessageCount: z.number().int().nonnegative().max(20),
    modelCalled: z.boolean(),
    modelLatencyMs: z.number().int().nonnegative().nullable(),
    modelTokenUsage: z.object({
      prompt: z.number().int().nonnegative().nullable(),
      output: z.number().int().nonnegative().nullable(),
      total: z.number().int().nonnegative().nullable(),
    }).strict(),
    modelUsageSource: z.enum(["provider", "estimated", "missing"]).optional(),
    modelPath: z.enum([
      "not_called",
      "model",
      "initial_fallback",
      "grounded_fallback",
      "grounded_draft_fallback",
    ]).optional(),
    modelErrorClass: z.string().max(128).nullable().optional(),
    buyingSignalOverride: z.boolean(),
    wave2Strategy: z.object({
      rulesetVersion: z.literal("wave2-strategy-v1"),
      need: z.enum([
        "NEED_OCCASION",
        "NEED_STYLE",
        "NEED_BUDGET",
        "NOT_ENOUGH_CONTEXT",
      ]),
      barrier: z.enum([
        "NONE",
        "BARRIER_PRICE",
        "BARRIER_FIT",
        "BARRIER_MATERIAL",
        "BARRIER_TRUST",
        "BARRIER_DELIVERY",
        "CHOICE_OVERLOAD",
      ]),
      decisionFactor: z.enum([
        "OCCASION",
        "STYLE",
        "BUDGET",
        "FIT",
        "MATERIAL",
        "TRUST",
        "DELIVERY",
        "PRODUCT",
        "UNKNOWN",
      ]),
      recommendedStrategy: z.enum([
        "STRATEGY_RECOMMEND_PRODUCT",
        "STRATEGY_SHOW_PROOF",
        "STRATEGY_ANSWER_OBJECTION",
        "STRATEGY_ASK_CLARIFY",
        "STRATEGY_CLOSE",
      ]),
      ctaPolicy: z.enum([
        "ASK_OCCASION",
        "ASK_STYLE",
        "ASK_BUDGET",
        "ASK_MEASUREMENTS",
        "ASK_PROOF_PREFERENCE",
        "REDUCE_TO_TWO",
        "POST_MEDIA_CLOSE",
        "NO_ADDITIONAL_CTA",
      ]),
      confidence: z.number().min(0).max(1),
      evidence: z.array(z.string().min(1).max(64)).max(16),
      experimentId: z.literal("wave2-stage-playbook-v1"),
      experimentVariant: z.literal("LIVE_100"),
    }).strict().nullable().optional(),
    decisionObservability: DecisionObservabilityV1Schema.optional(),
  }).strict(),
}).strict();

export type RealtimeDecisionEventType = z.infer<typeof RealtimeDecisionEventTypeSchema>;
export type RealtimeDecisionEventV1 = z.infer<typeof RealtimeDecisionEventV1Schema>;
